### ISSUE TITLE
ValueError: 6 columns passed, passed data had 5 columns

### ISSUE THREAD

**Issue by X-zhihao** [LogIntelligence/LogADEmpirical#13]
I follow README.md demo shell script，and I got this error.
Please tell me how to change the parameter to avoid this problem.

**Comment by X-zhihao** [comment]
Traceback (most recent call last):
  File "/data_disk/logAdSum/main_run.py", line 213, in <module>
    main()
  File "/data_disk/logAdSum/main_run.py", line 171, in main
    train_size=args.train_size, random_sample=args.random_sample, session_type=args.session_level)
  File "/data_disk/logAdSum/logadempirical/dataset/data_process.py", line 127, in process_dataset
    "step_size": step_size}).to_dict("records")
  File "/data_disk/logAdSum/logadempirical/logdeep/dataset/session.py", line 133, in sliding_window
    pd.DataFrame(new_data, columns=raw_data.columns)
  File "/data_disk/anaconda3/envs/tranad/lib/python3.7/site-packages/pandas/core/frame.py", line 570, in __init__
    arrays, columns = to_arrays(data, columns, dtype=dtype)
  File "/data_disk/anaconda3/envs/tranad/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 528, in to_arrays
    return _list_to_arrays(data, columns, coerce_float=coerce_float, dtype=dtype)
  File "/data_disk/anaconda3/envs/tranad/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 571, in _list_to_arrays
    raise ValueError(e) from e
ValueError: 6 columns passed, passed data had 5 columns

Process finished with exit code 1

**Comment by benpaobamingliang1** [comment]
hello , We can communicate as follows, my WeChat ID is 18211741109

**Comment by mateuszkochanek** [comment]
I have the same problem, what is the solution?

**Comment by souravs17031999** [comment]
@mateuszkochanek @X-zhihao were you able to resolve this issue ? I am having the same error.

**Comment by mateuszkochanek** [comment]
@souravs17031999 Not yet, I had other work to do this past week, but I'm coming back to this at Tuesday. If you find anything please share.

**Comment by pupuu555** [comment]
> 

hi,have you find the way to solve this issue?I meet the same problem now.

**Comment by sailormoon-c** [comment]
> 

same problems for me. Have you solved this?

**Comment by znagzanglong** [comment]
I also encountered the same problem and it has not been resolved.

**Comment by louki-vn** [comment]
I have same problem. How to fix it?

**Comment by X-zhihao** [comment]
I think this is not a complete and correct code. Fixing it might be a waste of time since it won't run at all.

**Comment by vanhoanglepsa** [comment]
> I have same problem. How to fix it?

This repo is under extension. Plz refer to the [dev](https://github.com/LogIntelligence/LogADEmpirical/tree/dev) branch, which is up-to-date.

**Comment by MingYueManQianShan** [comment]
Maybe it's because the parameters of your command are incorrect, you'd better check them.

**Comment by yi-sa-sa** [comment]
> Maybe it's because the parameters of your command are incorrect, you'd better check them.

I don't know if you run through this code, if you run through can ask for communication
